# Note: This base file is not built from the Dockerfile_compiler.base image
# Note: This base image is built from the Dockerfile_compiler.base image. After the container is running, it was manually re-installed with gcc-multilib, and then gcc-arm-linux-gnueabi.
# Note: After saving it as a base image with git commit, it is used as the base image for this image.
# Repeat installation instructions: Installing gcc-multilib is because it will prompt for missing .h files if it is not installed. However, it will overwrite the original gcc-arm-linux-gnueabi, so you need to install gcc-arm-linux-gnueabi again. If all gcc-multilib and gcc-arm-linux-gnueabi are uninstalled from the Dockerfile, repeating the installation will result in an error.
FROM tbox-compiler:latest

# First, copy all the libjansson and libpaho-mqtt3a, libpaho-mqtt3c dependent libraries compiled by the program to the context's lib directory
WORKDIR /root/tbox
COPY ./lib/* /usr/local/lib/
COPY ./lib/* /usr/lib/
# First, copy all the header files of libjansson and libpaho-mqtt3a, libpaho-mqtt3c compiled by the program to the context's include directory
COPY ./include/* /usr/local/include/
COPY ./include/* /usr/include/

ENTRYPOINT ["bash", "make.sh"]
