FROM ubuntu:22.04

# 安装相关的软件包
RUN apt-get update && apt-get install -f -y --no-install-recommends build-essential gcc make cmake cmake-gui cmake-curses-gui libssl-dev  libc6-dev  gcc-arm-linux-gnueabi

WORKDIR /root
RUN [ -d /usr/local/ ] || mkdir -p /usr/local/ && mkdir -p /usr/local/lib/
COPY ./lib/* /usr/local/lib/
COPY ./lib/* /usr/lib/


ENTRYPOINT ["bash"]
