version: '2'

services:

  tbox:
    image: docker-server/docker-org/can_qemu:image-version
    restart: always
    container_name: tbox
    privileged: true
    network_mode: "host"
    environment:
      - debug_env_flag=1