apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbox
  template:
    metadata:
      labels:
        app: tbox
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      hostNetwork: true ## network_mode: "host"
      containers:
        - name: tbox
          image: docker-server/docker-org/can_qemu:image-version
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "356Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: hwbj
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tbox
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{"type":"public","bandwidth_name":"cce-bandwidth-1551163379627","bandwidth_chargemode":"traffic","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_bgp","name":"james"}'
    kubernetes.io/elb.enterpriseID: '0'     # 负载均衡所属企业项目ID
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN                   # 负载均衡器算法
    kubernetes.io/elb.session-affinity-mode: SOURCE_IP          # 会话保持类型为源IP
    kubernetes.io/elb.session-affinity-option: '{"persistence_timeout": "30"}'     # 会话保持时间（分钟）
    kubernetes.io/elb.health-check-flag: 'on'                   # 开启ELB健康检查功能
    kubernetes.io/elb.health-check-option: '{"protocol":"TCP","delay":"5","timeout":"10","max_retries":"3"}'
spec:
  selector:
    app: tbox  
  type: LoadBalancer